"""add student bot state

Revision ID: 24db613c0e55
Revises: 5e2f14a8eecd
Create Date: 2026-06-30 13:10:17.930544
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "24db613c0e55"
down_revision: str | None = "5e2f14a8eecd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "student_bot_states",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("idle", "awaiting_homework", name="conversation_state", native_enum=False),
            nullable=False,
        ),
        sa.Column("assignment_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["assignments.id"],
            name=op.f("fk_student_bot_states_assignment_id_assignments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_student_bot_states_student_id_students"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("student_id", name=op.f("pk_student_bot_states")),
    )
    op.create_index(
        op.f("ix_student_bot_states_assignment_id"),
        "student_bot_states",
        ["assignment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_student_bot_states_assignment_id"), table_name="student_bot_states")
    op.drop_table("student_bot_states")
    # ### end Alembic commands ###
