"""add submission review timestamp

Revision ID: 5d85c88a25c0
Revises: a126d6def531
Create Date: 2026-06-30 13:35:09.332161
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5d85c88a25c0"
down_revision: str | None = "a126d6def531"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "submissions", sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("submissions", "reviewed_at")
    # ### end Alembic commands ###
