"""add course slug

Revision ID: 5e2f14a8eecd
Revises: fdbca245dfbb
Create Date: 2026-06-30 13:00:25.216374
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5e2f14a8eecd"
down_revision: str | None = "fdbca245dfbb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("courses", sa.Column("slug", sa.String(length=100), nullable=False))
    op.create_index(op.f("ix_courses_slug"), "courses", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_courses_slug"), table_name="courses")
    op.drop_column("courses", "slug")
    # ### end Alembic commands ###
